### ISSUE TITLE
r10k won't update a changed module if the tag is correct

### ISSUE THREAD

**Issue by bhasterix** [puppetlabs/r10k#583] opened 2016-04-13 08:26 UTC
If I've published my code with r10k (based on tag) and manually edit a file in one of my modules (accidentally/on purpose/some junior did it) and rerun r10k deployment it doesn't pick up that there was a change so doesn't try to pull again.

Steps:
# Deploys current version

r10k deploy environment development
# Redeploy current version

r10k deploy environment development -p -v debug
[...]
# [2016-04-11 16:55:22 - INFO] Environment development is now at 43ac0c410316c6ed1ab38fc5787bb0974e674e63
# [2016-04-11 16:55:22 - INFO] Deploying module /etc/puppetlabs/code/environments/development/modules/apache
# [2016-04-11 16:55:24 - DEBUG] /etc/puppetlabs/code/environments/development/modules/apache is already at Git ref master
# [...]
# Change something manually:

echo "brian" >> /etc/puppetlabs/code/environments/development/modules/apache/metadata.json
# Redeploy current version

r10k deploy environment development -p -v debug
[...]
# [2016-04-11 16:58:15 - INFO] Deploying environment /etc/puppetlabs/code/environments/development
# [2016-04-11 16:58:16 - DEBUG] /etc/puppetlabs/code/environments/development is already at Git ref development
# [2016-04-11 16:58:16 - INFO] Environment development is now at 43ac0c410316c6ed1ab38fc5787bb0974e674e63
# [2016-04-11 16:58:16 - INFO] Deploying module /etc/puppetlabs/code/environments/development/modules/apache
# [2016-04-11 16:58:18 - DEBUG] /etc/puppetlabs/code/environments/development/modules/apache is already at Git ref master
# [...]

And then we're left with the manually edited file incorrectly.

So now, if I change my Puppetfile to use a different version of my module and deploy again it will detect that there are local changes and stop the switch to the new version, but it all seems to hinge on git's checkout based on tag. It might be better to base it on a reset rather than checkout:

[root@dubxpcvm906 apache]# git checkout tags/v0.1.0
Previous HEAD position was 5d40cdd... Update apache module to 1.8.1
HEAD is now at 94035ac... Initialise apache module

[root@dubxpcvm906 apache]# git checkout tags/v0.1.1
Previous HEAD position was 94035ac... Initialise apache module
HEAD is now at 5d40cdd... Update apache module to 1.8.1

[root@dubxpcvm906 apache]# nano metadata.json # make change

[root@dubxpcvm906 apache]# git checkout tags/v0.1.1 # checkout same again, no check performed, already at correct ref for tag.
M    metadata.json
HEAD is now at 5d40cdd... Update apache module to 1.8.1

[root@dubxpcvm906 apache]# git checkout tags/v0.1.0
error: You have local changes to 'metadata.json'; cannot switch branches.

So then I suppose realistically it should have a git reset to ref/tag:
[root@dubxpcvm906 apache]# git reset --hard v0.1.1
warning: refname 'v0.1.1' is ambiguous.
warning: refname 'v0.1.1' is ambiguous.
HEAD is now at 5d40cdd Update apache module to 1.8.1
[root@dubxpcvm906 apache]# nano metadata.json
[root@dubxpcvm906 apache]# git reset --hard v0.1.0
warning: refname 'v0.1.0' is ambiguous.
warning: refname 'v0.1.0' is ambiguous.
HEAD is now at 94035ac Initialise apache module

No issue and it's reverted properly...

**Comment by hybby** [comment] 2016-05-31 22:31
I've encountered this, too (on R10K 1.5.1, Ruby 1.8.7).  **EDIT: Also confirmed in R10K 2.3.0, Ruby 2.3.0**

Steps to reproduce:
- Run `r10k deploy environment master`
- Change to environment directory.  Remove some file / directory.
- Re-run `r10k deploy environment master`
- List contents of environment.  Removed file is not restored.

Output:

```
root@vagrant:/etc/puppet/environments# r10k deploy environment master --verbose debug
[2016-05-31 23:16:02 - DEBUG] Fetching 'git@github.com:hybby/puppet.git' to determine current branches.
[2016-05-31 23:16:09 - INFO] Deploying environment /etc/puppet/environments/master
[2016-05-31 23:16:09 - DEBUG] Cloning /etc/puppet/environments/master and checking out master
[2016-05-31 23:16:16 - DEBUG] Environment master is new, updating all modules

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  firewall  motd  rootuser  selinux  sshd

root@vagrant:/etc/puppet/environments/master/modules# rm -rf firewall/

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  motd  rootuser  selinux  sshd

root@vagrant:/etc/puppet/environments/master/modules# r10k deploy environment master --verbose debug
[2016-05-31 23:19:01 - DEBUG] Fetching 'git@github.com:hybby/puppet.git' to determine current branches.
[2016-05-31 23:19:08 - INFO] Deploying environment /etc/puppet/environments/master
[2016-05-31 23:19:09 - DEBUG] /etc/puppet/environments/master is already at Git ref master

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  motd  rootuser  selinux  sshd
```

In this case, what I'd expect to happen is for R10K to notice that I've removed a file and that it doesn't match origin anymore.  It should correctly restore the removed directory.

It's worth noting that this behaviour did _not_ affect version 1.3.4, which I'm upgrading from:

```
root@vagrant:/etc/puppet/environments# r10k _1.3.4_ deploy environment master --verbose debug
[R10K::Source::Git - INFO] Determining current branches for "git@github.com:hybby/puppet.git"
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment master
[R10K::Environment::Git - DEBUG] Environment /etc/puppet/environments/master is a fresh clone; automatically updating modules.
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  firewall  motd  rootuser  selinux  sshd

root@vagrant:/etc/puppet/environments/master/modules# rm -rf firewall/

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  motd  rootuser  selinux  sshd

root@vagrant:/etc/puppet/environments/master/modules# r10k _1.3.4_ deploy environment master --verbose debug
[R10K::Source::Git - INFO] Determining current branches for "git@github.com:hybby/puppet.git"
[R10K::Task::Environment::Deploy - NOTICE] Deploying environment master
[R10K::Task::Deployment::PurgeEnvironments - INFO] Purging stale environments from /etc/puppet/environments

root@vagrant:/etc/puppet/environments/master/modules# ls
dns  dotfiles  firewall  motd  rootuser  selinux  sshd
```

What changed?  I can't see anything relevant in the changelog.

**Comment by hybby** [comment] 2016-06-01 00:52
It looks like this behaviour changed when `lib/r10k/git/stateful_repository.rb` was introduced (1.5.0).  There's no determining whether the working directory has had any non-staged changes made to it (additions, deletions, removals) during a deployment.  In 1.3.4, I presume a full clone was carried out regardless.

I've managed to hack in the functionality that I think should be there with [this PR](https://github.com/puppetlabs/r10k/pull/603) - however, I'm no Ruby dev - I'd appreciate if someone from the R10K team could ratify this idea and determine whether there's a way they'd prefer this to be implemented?

With the patches included above, I get the behaviour that's expected:

```
# remove environment completely
root@vagrant:/# rm -rf /etc/puppet/environments/master/

# deploy environment, fresh.
root@vagrant:/# r10k deploy environment master --verbose debug
[2016-06-01 01:36:50 - WARN] The r10k configuration file at /etc/r10k.yaml is deprecated.
[2016-06-01 01:36:50 - WARN] Please move your r10k configuration to /etc/puppetlabs/r10k/r10k.yaml.
[2016-06-01 01:36:50 - DEBUG] Fetching 'git@github.com:hybby/puppet.git' to determine current branches.
[2016-06-01 01:36:56 - INFO] Deploying environment /etc/puppet/environments/master
[2016-06-01 01:36:56 - DEBUG] Cloning /etc/puppet/environments/master and checking out master
[2016-06-01 01:37:05 - INFO] Environment master is now at fb00587ea2ca36ed0ed6858738460f176fc23e7f
[2016-06-01 01:37:05 - DEBUG] Environment master is new, updating all modules

# check what modules we have
root@vagrant:/# ls /etc/puppet/environments/master/modules/
dns  dotfiles  firewall  motd  rootuser  selinux  sshd

# remove a module
root@vagrant:/# rm -rf /etc/puppet/environments/master/modules/firewall/

# check it's gone
root@vagrant:/# ls /etc/puppet/environments/master/modules/
dns  dotfiles  motd  rootuser  selinux  sshd

# redeploy environment
root@vagrant:/# r10k deploy environment master --verbose debug
[2016-06-01 01:37:19 - WARN] The r10k configuration file at /etc/r10k.yaml is deprecated.
[2016-06-01 01:37:19 - WARN] Please move your r10k configuration to /etc/puppetlabs/r10k/r10k.yaml.
[2016-06-01 01:37:19 - DEBUG] Fetching 'git@github.com:hybby/puppet.git' to determine current branches.
[2016-06-01 01:37:26 - DEBUG] Found 7 changes unstaged in workdir
[2016-06-01 01:37:26 - INFO] Deploying environment /etc/puppet/environments/master
[2016-06-01 01:37:26 - DEBUG] Found 7 changes unstaged in workdir
[2016-06-01 01:37:26 - DEBUG] Replacing /etc/puppet/environments/master and checking out master
[2016-06-01 01:37:32 - INFO] Environment master is now at fb00587ea2ca36ed0ed6858738460f176fc23e7f

# check that removed file has been restored
root@vagrant:/# ls /etc/puppet/environments/master/modules/
dns  dotfiles  firewall  motd  rootuser  selinux  sshd
```

**Comment by scotje** [comment] 2016-06-03 20:37
@hybby Your PR looks like a reasonable approach to this, I'll have to research an equivalent solution for the rugged/libgit2 backend and evaluate the performance implications but we should be able to get this resolved before the next release.

**Comment by hybby** [comment] 2016-06-06 19:32
Excellent news.  Thanks for the feedback, @scotje.

**Comment by scotje** [comment] 2016-06-06 20:54
Created https://tickets.puppetlabs.com/browse/RK-248 to track this in JIRA.

**Comment by scotje** [comment] 2016-07-05 16:49
This should be resolved once https://github.com/puppetlabs/r10k/pull/617 is merged which should be happening this week sometime.

**Comment by scotje** [comment] 2016-08-22 17:10
This should now be resolved, let me know if you are still running into the issue in the latest releases.

**Closed as completed by scotje** 2016-08-22 17:10 UTC
