### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by m4ce** [puppetlabs/r10k#760] opened 2017-08-07 16:05 UTC
Using r10k 2.5.5 and Puppet 5.0.1 (AIO), bumping into this whenever I invoke r10k.

```
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/hiera.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/puppet.gemspec]: stack level too deep
```

Anyone knows how to go about it?

**Comment by libbymo** [comment] 2017-08-22 17:45
We're currently looking into this, and hope to have a fix in the next release of r10k.

**Comment by haus** [comment] 2017-08-22 23:34
@m4ce I'm having a little trouble reproducing this, could you post the results of `/opt/puppetlabs/puppet/bin/gem list` and the installation steps you followed (also the platform you're on, even though that shouldn't matter)?

**Comment by m4ce** [comment] 2017-08-23 10:56
@haus, see the output below:

```
*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
blankslate (2.1.2.4)
colored (1.2)
cri (2.6.1)
deep_merge (1.0.1)
did_you_mean (1.1.0)
docker-api (1.33.6)
excon (0.55.0)
facter (3.7.1)
faraday (0.9.2)
faraday_middleware (0.10.1)
fast_gettext (1.1.0)
gettext (3.2.2)
gettext-setup (0.24)
hiera (3.4.0)
hocon (1.2.5)
io-console (default: 0.4.6)
json (default: 2.0.2)
locale (2.1.2)
log4r (1.1.10)
minitar (0.6.1, 0.5.4)
minitest (5.10.1)
multi_json (1.12.1)
multipart-post (2.0.0)
nats-pure (0.2.4)
net-ssh (4.1.0)
net-telnet (0.1.1)
openssl (default: 2.0.3)
parslet (1.5.0)
power_assert (0.4.1)
psych (default: 2.2.2)
puppet (5.0.1)
puppet_forge (2.2.6)
r10k (2.5.5)
rake (12.0.0)
rdoc (default: 5.0.0)
semantic_puppet (0.1.2)
stomp (1.3.3)
test-unit (3.2.3)
text (1.3.1)
toml (0.1.2)
xmlrpc (0.2.1)
```

I've built a custom puppet-agent (just added new rubygems components really), but I have been doing this for a while now and never saw any issue. The platform is RHEL 7.2.

**Comment by haus** [comment] 2017-08-23 15:38
@m4ce would you be willing to see if the change in https://github.com/puppetlabs/r10k/pull/755 makes any difference in your situation? That was one of the routes I was pursuing when investigating this.

**Comment by m4ce** [comment] 2017-08-23 20:28
So, I had to update to puppet_forge 2.2.7 as 2.2.6 depends on ~> 0.1.0.

However, the problem seemed to get only worse:

```
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/hiera.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/puppet.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/faraday-0.9.2.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/faraday-0.9.2.gemspec]: stack level too deep
```

If I downgrade to puppet_forge 2.2.6, the faraday 'stack level too deep' goes away.

**Comment by haus** [comment] 2017-08-23 21:36
Alright. That's too bad. Which custom gems did you add to your puppet-agent build?

**Comment by haus** [comment] 2017-08-23 21:42
Or if you have a link to your custom puppet-agent build I can try using/looking at that for reproduction.

**Comment by m4ce** [comment] 2017-08-24 07:16
colored 1.2
cri 2.6.1
docker-api 1.33.6
excon 0.55.0
faraday 0.9.2
faraday_middleware 0.10.1
log4r 1.1.10
minitar 0.5.4
multi_json 1.12.1
multipart-post 2.0.0
nats-pure 0.2.4
parslet 1.5.0
puppet_forge 2.2.0
r10k 2.5.5
toml 0.1.2

**Comment by tmuhonkin** [comment] 2017-08-28 11:01
Hi! I get this message after upgrade gettext (3.2.2) -> gettext (3.2.4)
Identity added: /home/deploy/.ssh/id_rsa (/home/deploy/.ssh/id_rsa)
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/hiera.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/puppet.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/text-1.3.1.gemspec]: stack level too deep
Invalid gemspec in [/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/specifications/text-1.3.1.gemspec]: stack level too deep

Мy gems is:

root@puppet5-master-1:~# /opt/puppetlabs/puppet/bin/gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
colored (1.2)
cri (2.6.1)
deep_merge (1.0.1)
did_you_mean (1.1.0)
facter (3.8.0)
faraday (0.9.2)
faraday_middleware (0.10.1)
fast_gettext (1.1.0)
gettext (3.2.2)
gettext-setup (0.26)
hiera (3.4.0)
hocon (1.2.5)
io-console (default: 0.4.6)
json (default: 2.0.2)
locale (2.1.2)
log4r (1.1.10)
minitar (0.6.1)
minitest (5.10.1)
multi_json (1.12.1)
multipart-post (2.0.0)
net-ssh (4.1.0)
net-telnet (0.1.1)
openssl (default: 2.0.3)
power_assert (0.4.1)
psych (default: 2.2.2)
puppet (5.1.0)
puppet_forge (2.2.6)
r10k (2.5.5)
rake (12.0.0)
rdoc (default: 5.0.0)
semantic_puppet (0.1.2)
stomp (1.3.3)
test-unit (3.2.3)
text (1.3.1)
xmlrpc (0.2.1)
yaml-lint (0.0.9)

**Comment by haus** [comment] 2017-08-28 23:55
I'll try again to reproduce this tomorrow.

**Comment by haus** [comment] 2017-08-29 22:41
Okay, for all those watching, I have an explanation, but not an immediate fix. The tl;dr; is that if you have puppet-agent installed, you cannot have more than 1 version of any gem that r10k depends on installed.

In @tmuhonkin 's case, gettext is a dependency of r10k, so having both 3.2.2 and 3.2.4 installed at the same time exposes the issue. 

In @m4ce 's case, minitar is present at version 0.5.4 and r10k requires version 0.6.1 (I think at least?).

The more complete answer seems to be that when more than 1 version of a dependency of r10k is available, rubygems loads all of the gemspecs it can find, including hiera and puppet. When it tries to parse hiera's gemspec, it gets to this line https://github.com/puppetlabs/hiera/blob/master/.gemspec#L9 which tries to require `hiera/version`. Rubygems monkey patches Kernel.require to first search gems for the dependency before searching the load path, so at this point, rubygems loads all of the gemspecs it can find trying to load `hiera/version`. It again finds the hiera gemspec, which tries to require `hiera/version`, and this horrific circle continues until the stack is exhausted.
In the happy case, when there is only 1 version of a dependency, hiera and puppet are never loaded.

I think the correct fix here is to update puppet and hiera to simply hard code their versions into the gemspec, so that the above situation no longer happens. I'll be opening tickets and PRs into the respective projects to accomplish that.

**Comment by haus** [comment] 2017-08-29 23:09
I've opened https://github.com/puppetlabs/puppet/pull/6162 (https://tickets.puppetlabs.com/browse/PUP-7889) and https://github.com/puppetlabs/hiera/pull/403 (https://tickets.puppetlabs.com/browse/HI-579) to try to get the ball rolling on this.

**Comment by haus** [comment] 2017-10-02 21:40
The above changes have shipped in recent puppet-agent 5 releases (5.3.0 and later I believe). I'd be interested to know if that build addresses the problem for people.

**Comment by andersonmills** [comment] 2017-11-09 19:42
@m4ce and @tmuhonkin can you try this out?

**Comment by m4ce** [comment] 2017-11-13 09:00
@andersonmills, using the latest puppet release (5.3.x) solves this issue! Thanks!

**Comment by andersonmills** [comment] 2017-11-13 17:26
Rockin! Closing this issue.

**Closed as completed by andersonmills** 2017-11-13 17:26 UTC
