### ISSUE TITLE
R10K::Action::Puppetfile::Check cannot handle option 'help'

### ISSUE THREAD

**Issue by aadamovich** [puppetlabs/r10k#936] opened 2019-06-02 21:19 UTC
When running r10k 3.2.0 with puppet 6.4.2 on Ubuntu 16.04 I get the following error:

```
# /opt/puppetlabs/puppet/bin/r10k puppetfile check --verbose=9 --trace --puppetfile /tmp/deploy-puppet/Puppetfile

r10k: Runtime error: #<ArgumentError: R10K::Action::Puppetfile::Check cannot handle option 'help'>
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/util/setopts.rb:49:in `block in setopts'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/util/setopts.rb:35:in `each_pair'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/util/setopts.rb:35:in `setopts'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/base.rb:18:in `initialize'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb:23:in `new'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb:23:in `instance'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb:33:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/cri_runner.rb:67:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command_dsl.rb:303:in `block in runner'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:369:in `run_this'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:296:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:314:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:314:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/bin/r10k:7:in `<top (required)>'
/opt/puppetlabs/puppet/bin/r10k:23:in `load'
/opt/puppetlabs/puppet/bin/r10k:23:in `<main>'

```

I managed to workaround the problem by adding `iopts.delete(:help)` line into /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb file:

```
module R10K
  module Action
    class Runner
      include R10K::Logging

      def initialize(opts, argv, klass)
        @opts = opts
        @argv = argv
        @klass = klass

        @settings = {}
      end

      def instance
        if @_instance.nil?
          iopts = @opts.dup
          iopts.delete(:loglevel)
          iopts.delete(:help)
          @_instance = @klass.new(iopts, @argv, @settings)
        end
        @_instance
      end

```

But obviously, it's not a proper solution. What can be wrong? Is it because of the latest Puppet/Ruby version or is it something else?

**Comment by freibuis** [comment] 2019-06-03 02:56
This is a similar issue here running r10k 3.2.0 with ruby 2.6.3 (or ruby 2.5.3 supplied with the puppet-agent) this only started happening a couple of days ago.
only on one server, I upgraded.
does not matter what I do I will get when trying deploy
```bash
r10k: Runtime error: #<NoMethodError: undefined method `[]=' for nil:NilClass>
```


```bash
/opt/puppetlabs/puppet/bin/r10k deploy display --trace

r10k: Runtime error: #<NoMethodError: undefined method `[]=' for nil:NilClass>
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb:49:in `setup_settings'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/runner.rb:30:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/lib/r10k/action/cri_runner.rb:67:in `call'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command_dsl.rb:303:in `block in runner'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:369:in `run_this'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:296:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:314:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/cri-2.15.7/lib/cri/command.rb:314:in `run'
/opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/r10k-3.2.0/bin/r10k:7:in `<top (required)>'
/opt/puppetlabs/puppet/bin/r10k:23:in `load'
/opt/puppetlabs/puppet/bin/r10k:23:in `<main>'
```

**Comment by freibuis** [comment] 2019-06-03 03:12
@aadamovich  I can confirm that doing a `r10k puppetfile check` causes me the same issue

**Comment by freibuis** [comment] 2019-06-03 03:15
Ok,
it looks like puppet 6.4.2 is causing the issue...   I rolled back to 6.4.1 and it now works for both @aadamovich  issue and the issue I had

if your project uses a Gemfile . a tempary workaround would be to hard lock it to the older version for now
```
gem 'puppet', '6.4.1'
```
hope this helps

**Comment by dylanratcliffe** [comment] 2019-06-03 09:47
This is caused by a change in CRI in [2.15.6](https://github.com/ddfreyne/cri/releases/tag/2.15.6). A patch release changed the data that CRI outputs and r10k no longer handles it (I'm assuming, given the CRI change refers to "help", I haven't dig into it too deeply). Pin your projects to a lower version while it's fixed in either r10k or cri:

```ruby
gem 'cri', '<= 2.15.5'
```

**Comment by freibuis** [comment] 2019-06-04 00:51
definitely is the `cri` change. I should have not been lazy and looked further ;)

anyway I can confirm moving puppet agent back to 6.4.2 and applying `cri` to 2.15.5 fixed this ..

@dylanratcliffe :+1:

**Comment by dylanratcliffe** [comment] 2019-06-04 07:17
I think r10k should still fix this internally though to handle the new object because loads of people will hit this. Reopening to track that

Edit: Haha apparently I accidentally closed this using a commit in a different project, didn't know that was possible.

**Comment by freibuis** [comment] 2019-06-04 11:28
r10k 3.3.0 has been deployed to rubyems.. this includes the hard locked `cri` dependency..
both issues listed above work.. so I would say that this would be fixed now.

**Comment by dylanratcliffe** [comment] 2019-06-04 11:35
Agreed :D

**Closed as completed by dylanratcliffe** 2019-06-04 11:35 UTC
