### ISSUE TITLE
R10K::Action::Puppetfile::Install cannot handle option 'config'>

### ISSUE THREAD

**Issue by ghost** [puppetlabs/r10k#294] opened 2015-02-03 15:14 UTC
Running install I can see the default .r10k cache directory for git but I had set this to another location in the yaml:

```
:cachedir: '/var/cache/r10k'
```

I was expecting the install command to use this cache location, this is useful for vagrant docker so I can share the cache between docker containers.

**Comment by adrienthebo** [comment] 2015-02-04 07:50
Duplicate of #105

**Closed as completed by adrienthebo** 2015-02-04 07:50 UTC
